2019-11-02 00:41:57,791-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 00:44:54,948-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 00:54:22,612-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 00:55:11,461-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 00:55:48,119-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 00:56:49,557-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 00:57:48,130-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 00:58:53,978-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 00:59:34,318-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:01:55,017-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:04:49,406-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:09:03,974-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:10:26,818-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:11:41,568-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:14:47,428-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:14:47,633-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:15:08,215-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:15:08,833-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:15:24,640-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:15:24,906-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:15:37,195-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:15:37,400-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:22:38,881-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:22:39,084-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:23:55,784-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:23:56,194-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:25:16,373-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-11-02 01:25:16,577-ERROR-Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\18521\PycharmProjects\imuke\Base\Base_request.py", line 33, in run_main
    res=json.loads(res)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18521\AppData\Local\Continuum\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
